name: Test behaviour

on: [push]

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_name: [ 'solo', 'language_variant', 'combined', 'dir', 'multiple_solo', 'multiple_combined' ]
    name: ${{ matrix.test_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./
        with:
          in-directory: test/${{ matrix.test_name }}
          out-directory: output

      - name: Processed languages
        shell: bash
        run: |
          echo "Processed languages: ${{ steps.test.outputs.languages }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.test_name }}
          path: output/
